AWSTemplateFormatVersion: 2010-09-09
Description: Create EC2 instance with a specified key pair

Resources:
  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d5eff06f840b45e9 # ImageID valid only in the us-east-1 region
      InstanceType: t2.micro
      KeyName: group_6_key  # Replace with your actual key pair name
      Tags:
        - Key: Name
          Value: snehal  # Replace with your desired instance name


  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: snehal-unique-bucket-name-2024 # Replace with a globally unique name
      Tags:
        - Key: Name
          Value: SnehalBucket  # Tag for the S3 bucket
