AWSTemplateFormatVersion: '2010-09-09'
Description: Infrastructure for Kaggle Data Processing Pipeline

Resources:
  RawDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: raw-data-bucket

  BootstrapScriptsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bootstrap-scripts-bucket


