AWSTemplateFormatVersion: '2010-09-09'
Description: Setup an AWS Glue Job with input and output directories in the same S3 bucket

Resources:
  # Existing Source and Destination S3 Bucket
  Group6DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: group6data # Ensure this is globally unique

  # Glue Job
  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: MyGlueJob
      Role: arn:aws:iam::494850518194:role/LabRole
      Command:
        Name: glueetl
        ScriptLocation: !Sub s3://group6data/scripts/PythonScript.txt.py # Path to the script
      DefaultArguments:
        '--job-language': 'python'
        '--TempDir': !Sub s3://group6data/temporary/
      MaxCapacity: 2
      GlueVersion: '2.0'
      ExecutionProperty:
        MaxConcurrentRuns: 1
