AWSTemplateFormatVersion: '2010-09-09'
Description: Infrastructure for Kaggle Data Processing Pipeline

Resources:
  RawDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: raw-data-bucket

  BootstrapScriptsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bootstrap-scripts-bucket

  EMRCluster:
    Type: AWS::EMR::Cluster
    Properties:
      Name: EMR Kaggle Data Pipeline
      ReleaseLabel: emr-6.5.0
      Applications:
        - Name: Hadoop
        - Name: Spark
      Instances:
        MasterInstanceGroup:
          InstanceCount: 1
          InstanceType: m5.xlarge
        CoreInstanceGroup:
          InstanceCount: 1
          InstanceType: m5.xlarge
          
