AWSTemplateFormatVersion: 2010-09-09
Description: Create EC2 instance

Resources:
  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d5eff06f840b45e9 # ImageID valid only in us-east-1 region
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: yogesh  # Replace with your desired instance name
Resources:
  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d5eff06f840b45e9 # ImageID valid only in us-east-1 region
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: Dnyanesh  # Replace with your desired instance name
