AWSTemplateFormatVersion: "2010-09-09"
Resources:
  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: MyGlueJob
      Role: arn:aws:iam::494850518194:role/GlueServiceRole  # Replace with your Glue role ARN
      Command:
        Name: glueetl
        ScriptLocation: s3://group6data/scripts/PythonScript.py
      DefaultArguments:
        '--job-language': 'python'
        '--TempDir': s3://group6data/temporary/
      MaxCapacity: 2
      GlueVersion: '3.0'
      ExecutionProperty:
        MaxConcurrentRuns: 1
