AWSTemplateFormatVersion: '2010-09-09'
Description: Create an EMR Cluster with Hadoop and Spark

Resources:
  EMRCluster:
    Type: AWS::EMR::Cluster
    Properties:
      Name: "EMR-Cluster-for-100MB-Data"
      ReleaseLabel: emr-6.10.0
      Applications:
        - Name: Hadoop
        - Name: Spark
      Ec2Attributes:
        KeyName: group_6_key  # Replace with your actual key pair name
      Instances:
        MasterInstanceGroup:
          InstanceCount: 1
          InstanceType: m5.xlarge
        CoreInstanceGroup:
          InstanceCount: 1
          InstanceType: m5.xlarge
        KeepJobFlowAliveWhenNoSteps: false
        TerminationProtected: false
        Ec2SubnetId: subnet-12345678  # Use your subnet ID
      LogUri: s3://dnyaneshbucket  # Replace with your S3 bucket URI
      JobFlowRole: EMR_EC2_DefaultRole
      ServiceRole: EMR_DefaultRole
      VisibleToAllUsers: true
      Tags:
        - Key: Name
          Value: EMR-Cluster
