AWSTemplateFormatVersion: 2010-09-09
Description: Create multiple EC2 instances

Resources:
  WebAppInstance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d5eff06f840b45e9 # ImageID valid only in us-east-1 region
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: snehal  # Instance 1 name

  WebAppInstance2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d5eff06f840b45e9 # ImageID valid only in us-east-1 region
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: D  # Instance 2 name

  WebAppInstance3:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d5eff06f840b45e9 # ImageID valid only in us-east-1 region
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: N  # Instance 3 name
          
