AWSTemplateFormatVersion: 2010-09-09
Description: Create an EC2 instance and an S3 bucket

Resources:
  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d5eff06f840b45e9 # ImageID valid only in the us-east-1 region
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: snehal  # Replace with your desired instance name

  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: snehal-unique-bucket-name-2024 # Replace with a globally unique name
      Tags:
        - Key: Name
          Value: SnehalBucket  # Tag for the S3 bucket
