AWSTemplateFormatVersion: '2010-09-09'
Description: Setup an AWS Glue Job with input and output directories in the same S3 bucket and a Glue Trigger for the Crawler

Resources:
  # Existing Source and Destination S3 Bucket
  Group6DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: group6data # Ensure this is globally unique


  MyEMRCrawlerTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Name: MyEMRCrawlerTrigger
      Type: ON_DEMAND
      Actions:
        - CrawlerName: MyEMRCrawlerName
      Predicate:
        Conditions:
          - LogicalOperator: EQUALS
            JobRunState:
              - SUCCEEDED
            CrawlerName: MyEMRCrawlerName
            State: SUCCEEDED
        Logical: AND
