AWSTemplateFormatVersion: '2010-09-09'
Description: Infrastructure for Kaggle Data Processing Pipeline

Resources:
  RawDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: raw-data-bucket

  BootstrapScriptsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bootstrap-scripts-bucket

AWSTemplateFormatVersion: 2010-09-09
Description: create ec2 instance
Resources:
  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d5eff06f840b45e9 # ImageID valid only in us-east-1 region
      InstanceType: t2.micro
