AWSTemplateFormatVersion: "2010-09-09"
Resources:
  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: MyGlueJob
      Role: arn:aws:iam::952084545413:role/aws_glue  # Replace with your Glue role ARN
      Command:
        Name: glueetl
        ScriptLocation: s3://newpiro/script/PythonScript.py
      DefaultArguments:
        '--job-language': 'python'
        '--TempDir': s3://newpiro/temp/
        '--input_bucket': newpiro
        '--input_directory': input
        '--output_bucket': newpiro
        '--output_directory': output
      MaxCapacity: 2
      GlueVersion: '3.0'
      ExecutionProperty:
        MaxConcurrentRuns: 1
      WorkerType: G.1X
      NumberOfWorkers: 2
      Description: "ETL job to transform data from input directory to output directory"
      Tags:
        Name: MyGlueJob
        Environment: Production
