---
AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template to create a Glue database, crawler, and ETL job using an existing IAM role.

Resources:
  GlueDatabase:
    Type: 'AWS::Glue::Database'
    Properties: 
      CatalogId: 494850518194
      DatabaseInput: 
        Name: my_database

  GlueCrawler:
    Type: 'AWS::Glue::Crawler'
    Properties:
      Role: arn:aws:iam::494850518194:role/LabRole
      DatabaseName: !Ref GlueDatabase
      Name: my_crawler
      Targets:
        S3Targets:
          - Path: 's3://group6data1/input/data.xlsx'
      Schedule:
        ScheduleExpression: 'cron(0 12 * * ? *)' # Run daily at 12:00 UTC

  GlueETLJob:
    Type: 'AWS::Glue::Job'
    Properties:
      Name: csv_to_parquet_job
      Role: arn:aws:iam::494850518194:role/LabRole
      Command:
        Name: glueetl
        ScriptLocation: 's3://group6data1/script/PythonScript.py'
        PythonVersion: '3'
      DefaultArguments:
        '--TempDir': 's3://group6data1/temp'
        '--job-bookmark-option': 'job-bookmark-enable'
      MaxRetries: 0
      Timeout: 2880
      GlueVersion: '2.0'
      NumberOfWorkers: 10
      WorkerType: G.1X

Outputs:
  GlueDatabaseName:
    Description: Name of the Glue Database
    Value: !Ref GlueDatabase

  GlueCrawlerName:
    Description: Name of the Glue Crawler
    Value: !Ref GlueCrawler

  GlueETLJobName:
    Description: Name of the Glue ETL Job
    Value: !Ref GlueETLJob
