---
AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template to create a Glue database, crawler, and ETL job using an existing IAM role.

Resources:
  # Output bucket to store processed data
  MyS3Bucket1:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: group6-transformation-output-data # Ensure this is a globally unique name
      Tags:
        - Key: group6
          Value: Output bucket for storing processed data

  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref "AWS::AccountId"
      DatabaseInput:
        Name: my_database

  GlueCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Role: arn:aws:iam::966884175598:role/LabRole
      DatabaseName: !GetAtt GlueDatabase.DatabaseInput.Name
      Name: my_crawler
      Targets:
        S3Targets:
          - Path: 's3://group6-project-data/input/HI-Small_Trans.csv' # Ensure this is a folder path

  GlueETLJob:
    Type: AWS::Glue::Job
    Properties:
      Name: csv_to_parquet_job
      Role: arn:aws:iam::966884175598:role/LabRole
      Command:
        Name: glueetl
        ScriptLocation: 's3://group6-project-data/script/transform_script.py'
        PythonVersion: '3'
      DefaultArguments:
        '--TempDir': 's3://group6-project-data/temp/'
        '--job-bookmark-option': 'job-bookmark-enable'
      MaxRetries: 0
      Timeout: 2880
      GlueVersion: '4.0'
      NumberOfWorkers: 2
      WorkerType: G.1X  # Corrected worker type

Outputs:
  GlueDatabaseName:
    Description: Name of the Glue Database
    Value: !GetAtt GlueDatabase.DatabaseInput.Name

  GlueCrawlerName:
    Description: Name of the Glue Crawler
    Value: !Ref GlueCrawler

  GlueETLJobName:
    Description: Name of the Glue ETL Job
    Value: !Ref GlueETLJob
