name: GlueJobCI-CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_GANU }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_GANU }}
          aws-region: us-east-1  # Replace with your AWS region

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file ec2.yml \
            --stack-name GlueJobStack \
            --parameter-overrides \
              InputBucket=newpiro \
              InputDirectory=input \
              OutputBucket=newpiro \
              OutputDirectory=output \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Start Glue Job
        run: |
          aws glue start-job-run \
            --job-name MyGlueJob
