name: GlueJobCI-CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file ec2.yml \
            --stack-name GlueJobStack \
            --parameter-overrides \
              InputBucket=newpiro \
              InputDirectory=input \
              OutputBucket=newpiro \
              OutputDirectory=output \
            --capabilities CAPABILITY_NAMED_IAM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_GANU }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_GANU }}
          AWS_DEFAULT_REGION: us-east-1

      - name: Start Glue Job
        run: |
          aws glue start-job-run \
            --job-name MyGlueJob
